<center>
    <h1><b>Chapter 1. Vectors, Matrices and Arrays</b></h1>
</center>


---


### **1.0 Introduction**


---


### **1.1 Creating a Vector**


**Problem**
- You need to create a vector

**Solution**
- Use Numpy to create a one-dimensional array:

In [2]:
#import library
import numpy as np

# Create a vector as a row
vector_row = np.array([1, 2, 3])

# Create a vector as a column
vector_column = np.array([[1],
                          [2],
                          [3]])

print(vector_row)
print(vector_column)

[1 2 3]
[[1]
 [2]
 [3]]


----

### **1.2 Creating a Matrix**

**Problem**
- You need to create a matrix

**Solution**
- Use Numpy to create a two-dimensional array:

In [4]:
#load library
import numpy as np

#Create a matrix 
matrix = np.array([[1, 2],
                   [1, 2],
                   [1, 2]])

print('Matrix:\n', matrix)

Matrix:
 [[1 2]
 [1 2]
 [1 2]]


In [6]:
matrix_object = np.mat([[1, 2],
                        [1, 2],
                        [1, 2]])

print(matrix_object)

[[1 2]
 [1 2]
 [1 2]]


----

### **1.3 Creating a Sparse Matrix**

**Problem**
- Given data with very few nonzero values, you want to efficiently represent it.

**Solution**
- Create a sparse matrix

In [7]:
#Load libraries
import numpy as np
from scipy import sparse

#Create a matrix 
matrix = np.array([[0, 0],
                   [0, 1],
                   [3, 0]])

#Create compressed sparse row (CSR) matrix
matrix_sparse = sparse.csr_matrix(matrix)
print(matrix_sparse)

  (1, 1)	1
  (2, 0)	3


In [8]:
#Create larger matrix 
matrix_large = np.array([[0, 0, 0, 0, 0, 0],
                         [0, 1, 0, 0, 0, 0],
                         [3, 0, 0, 2, 0, 0]])

#Create compressed sparse row (CSR) matrix
matrix_large_sparse = sparse.csr_matrix(matrix_large)

print(matrix_large_sparse)

  (1, 1)	1
  (2, 0)	3
  (2, 3)	2


----

### **1.4 Selecting Elements**

**Problem**
- You need to select one or more elements in a vector or matrix.

**Solution**
- NumPy's arrays make that easy

In [9]:
#Load library
import numpy as np

#Create row vector 
vector = np.array([1, 2, 3, 4, 5, 6])

#Create matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

#Select third element of vector
print(vector[2])

#Select second row, second column
print(matrix[1, 1])

3
5


----


### **1.5 Describing a Matrix**

**Problem**
- You want to describe the shape, size and dimensions of the matrix

**Solution**
- Use `shape`, `size` and `ndim`:

In [10]:
#Load library
import numpy as np

#Create matrix 
matrix = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12]])

#View number of rows and columns
print(matrix.shape)

#View number of elements (rows * columns)
print(matrix.size)

#View number of dimensions
print(matrix.ndim)

(3, 4)
12
2


----

### **1.6 Apply Operations to Elements**

**Problem**
- You want to apply some function to multiple elements in an array

**Solution**
- Use Numpy's vectorize:

In [11]:
#Load library
import numpy as np

#Create matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

#Cerate function that adds 100 to something
add_100 = lambda i: i + 100

#Create vectorized function
vectorized_add_100 = np.vectorize(add_100)

#Apply fucntion to all elements in matrix
vectorized_add_100(matrix)

array([[101, 102, 103],
       [104, 105, 106],
       [107, 108, 109]])

----

### **1.7 Finding the Maximum and Minimum Values**

**Problem**
- You need to find the maximum or minimum value in an array.

**Solution**
- Use NumPy's max and min:

In [12]:
#Load library
import numpy as np

#Create matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

#return maximum element
print(np.max(matrix))

#Return minimum element
print(np.min(matrix))

9
1


----

### **1.8 Calculating the Average, Variance and Standard Deviation**

**Problem**
- You want to calculate some descriptive statistics about an array.

**Solution**
- Use NumPy's `mean`, `var` and `std`

In [1]:
#Load library 
import numpy as np

#Create matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

#Return mean
print(np.mean(matrix))

#Return variance
print(np.var(matrix))

#Return standard deviation
print(np.std(matrix))

5.0
6.666666666666667
2.581988897471611


In [2]:
#Find the mean value in each column
print(np.mean(matrix, axis=0))

#Find the mean value in each row
print(np.mean(matrix, axis=1))

[4. 5. 6.]
[2. 5. 8.]


----

### **1.9 Reshaping Arrays**

**Problem**
- You want to change the shape (number of rows and columns) of an array without changing the element values

**Solution**
- Use Numpy's `reshape`

In [4]:
#Load library
import numpy as np

#Create 4x3 matrix 
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9],
                   [10, 11, 12]])

#Reshape matrix into 2x6 matrix
print(matrix.reshape(2, 6))

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


----

### **1.10 Transposing a Vector or Matrix**

**Problem**
- You need to transpose a vector or matrix

**Solution**
- Use the `T` method:

In [6]:
#Load library
import numpy as np

#Create matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

print(matrix.T)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


----

### **1.11 Flattening a Matrix**

**Problem**
- You need to transform a matrix into a one-dimensional array.

**Solution**
- Use `flatten`

In [8]:
#Load library
import numpy as np

#Create matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

#Flatten matrix
print(matrix.flatten())

#or use reshape method
print(matrix.reshape(1, -1))

[1 2 3 4 5 6 7 8 9]
[[1 2 3 4 5 6 7 8 9]]


----

### **1.12 Finding the Rank of a Matrix**

**Problem**
- You need to know the rank of a matrix

**Solution**
- Use NumPy's linear algebra method `matrix_rank`

In [9]:
#Load library
import numpy as np

#Create matrix
matrix = np.array([[1, 1, 1],
                   [1, 1, 10],
                   [1, 1, 15]])

#return matrix rank
print(np.linalg.matrix_rank(matrix))

2


----

### **1.13 Calculating the Determinant**

**Problem**
- You need to know the determinant

**Solution**
- Use NumPy's linear algebra method `det`:

In [10]:
#Load library
import numpy as np

#Create matrix
matrix = np.array([[1, 2, 3],
                   [2, 4, 6],
                   [3, 8, 9]])

print(np.linalg.det(matrix))

0.0


----

### **1.14 Getting the Diagonal of a Matrix**

**Problem**
- You need to get the diagonal elements of a matrix

**Solution**
- Use `diagonal`

In [11]:
#Load library
import numpy as np

#Create matrix
matrix = np.array([[1, 2, 3],
                   [2, 4, 6],
                   [3, 8, 9]])

#Return diagonal elemets
print(matrix.diagonal())

[1 4 9]


In [12]:
#Return diagonal one above the main diagonal
print(matrix.diagonal(offset=1))
print(matrix.diagonal(offset=2))

#Return diagonal one below the main diagonal
print(matrix.diagonal(offset=-1))
print(matrix.diagonal(offset=-2))

[2 6]
[3]
[2 8]
[3]


----

### **1.15 Calculating the Trace of a Matrix**

**Problem**
- You need to calculate the trace of matrix

**Solution**
- Use `trace`

In [13]:
#Load library
import numpy as np

#Create matrix
matrix = np.array([[1, 2, 3],
                   [2, 4, 6],
                   [3, 8, 9]])

#Return trace
print(matrix.trace())

14


----

### **1.16 Finding Eigenvalues and Eogenvectors**

**Problem**
- You need to find eigenvalues and eigenvectors of a square matrix.

**Solution**
- Use NumPy's `linalg.eig`:

In [1]:
#Load library
import numpy as np

#Create matrix
matrix = np.array([[1, -1, 3],
                   [1,  1, 6],
                   [3,  8, 9]])

# Calculate eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(matrix)

#View eigenvalues
print(eigenvalues)

#View eigenvectors
print(eigenvectors)

[13.55075847  0.74003145 -3.29078992]
[[-0.17622017 -0.96677403 -0.53373322]
 [-0.435951    0.2053623  -0.64324848]
 [-0.88254925  0.15223105  0.54896288]]


----

### **1.17 Calculating Dot Products**

**Problem**
- You need to calculate the dot product of two vectors.

**Solution**
- Use Numpy's `dot`

In [2]:
#Load library
import numpy as np

#Create two vectors
vector_a = np.array([1, 2, 3])
vector_b = np.array([4, 5, 6])

#Calculate dot product
print(np.dot(vector_a, vector_b))

32


In [3]:
#Calculate dot product
vector_a @ vector_b

32

----

### **1.18 Adding and Subtracting Matrices**

**Problem**
- You want to add or subtract two matrices

**Solution**
- Use NumPy's `add` and `subtract`

In [4]:
#Load library
import numpy as np

#Create matrix
matrix_a = np.array([[1, 1, 1],
                     [1, 1, 1],
                     [1, 1, 2]])

#Create matrix
matrix_b = np.array([[1, 3, 1],
                     [1, 3, 1],
                     [1, 3, 8]])

#Add two matrices
add_two_matrices = np.add(matrix_a, matrix_b)
print(add_two_matrices)

#Subtract two matrices
subtract_two_matrices = np.subtract(matrix_a, matrix_b)
print(subtract_two_matrices)

[[ 2  4  2]
 [ 2  4  2]
 [ 2  4 10]]
[[ 0 -2  0]
 [ 0 -2  0]
 [ 0 -2 -6]]


In [6]:
#Add two matrices
print(matrix_a + matrix_b)

#Subtract two matrices
print(matrix_a - matrix_b)

[[ 2  4  2]
 [ 2  4  2]
 [ 2  4 10]]
[[ 0 -2  0]
 [ 0 -2  0]
 [ 0 -2 -6]]


----

### **1.19 Multiplying Matrices**

**Problem**
- You want to multiply two matrices

**Solution**
- Use NumPy's `dot`

In [7]:
#Load library
import numpy as np

#Create matrix
matrix_a = np.array([[1, 1],
                     [1, 2]])

#Create matrix
matrix_b = np.array([[1, 3],
                     [1, 2]])

#Multiply two matrices
multiply_two_matrices = np.dot(matrix_a, matrix_b)
print(multiply_two_matrices)

[[2 5]
 [3 7]]


In [8]:
#Multiply two matrices
matrix_a @ matrix_b

array([[2, 5],
       [3, 7]])

In [9]:
#Multiply two matrices element-wise
matrix_a * matrix_b

array([[1, 3],
       [1, 4]])

----

### **1.20 Inverting a Matrix**


**Problem**
- You want to calculate the inverse of a square matrix

**Solution**
- Use NumPy's linear algebra `inv` method:

In [10]:
#Load library
import numpy as np

#Create matrix 
matrix = np.array([[1, 4],
                   [2, 5]])

#Calculate inverse of matrix
inv_matrix = np.linalg.inv(matrix)
print(inv_matrix)

[[-1.66666667  1.33333333]
 [ 0.66666667 -0.33333333]]


In [12]:
#Multiply matrix and its inverse
matrix @ np.linalg.inv(matrix)

array([[1.00000000e+00, 0.00000000e+00],
       [1.11022302e-16, 1.00000000e+00]])

----

### **1.21 Generating Random Values**

**Problem**
- You want to generate pseudorandom values

**Solution**
- Use NumPy's `random`

In [13]:
#Load library
import numpy as np

#Set seed
np.random.seed(0)

#Genrate three random floats between 0.0 and 1.0
np.random.random(3)

array([0.5488135 , 0.71518937, 0.60276338])

In [14]:
#Generate three random integers between 1 and 10
np.random.randint(0, 11, 3)

array([3, 7, 9])

In [16]:
#Draw three numbers from a normal distribution with mean 0.0
#and standard deviation of 1.0
np.random.normal(0.0, 1.0, 3)

array([-0.13309028, -0.1730696 , -1.76165167])

In [17]:
#Draw three number from a logistic distribution with mean 0.0 and scale or 1.0
np.random.logistic(0.0, 1.0, 3)

array([ 1.46416405, -0.08013416, -0.4356214 ])

In [18]:
#Draw three numbers greater than or equal to 1.0 and less than 2.0
np.random.uniform(1.0, 2.0, 3)

array([1.83607876, 1.33739616, 1.64817187])