<center>
    <h1>
        <b>Chapter 6. Handling Text</b>
    </h1>
</center>

---

### **6.0 Introduction**

---

### **6.1 Cleaning Text**


**Problem**
- You have some unstructured text data and want to complete some basic cleaning

**Solution**
- Using Python's core string operations, in particular `strip`, `replace`, and `split`

In [3]:
#Create text
text_data = ["   Interrobang. By Aishwarya Henriette    ",
            "Parking And Going. By Karl Gautier  ",
            "  Today Is The night. By Jarek Prakash  "]

#Strip whitespaces
strip_whitespaces = [string.strip() for string in text_data]

#Show text
strip_whitespaces

['Interrobang. By Aishwarya Henriette',
 'Parking And Going. By Karl Gautier',
 'Today Is The night. By Jarek Prakash']

In [4]:
#Remove periods
remove_periods = [string.replace(".", "") for string in strip_whitespaces]

#show text
remove_periods

['Interrobang By Aishwarya Henriette',
 'Parking And Going By Karl Gautier',
 'Today Is The night By Jarek Prakash']

Create and apply a custom transformation function

In [5]:
#Create function
def capitalizer(string: str) -> str:
    return string.upper()

#Apply function
[capitalizer(string) for string in remove_periods]

['INTERROBANG BY AISHWARYA HENRIETTE',
 'PARKING AND GOING BY KARL GAUTIER',
 'TODAY IS THE NIGHT BY JAREK PRAKASH']

Use regular expressions to make powerful string operations

In [6]:
#Import library
import re

#Create function
def replace_letters_with_x(string: str) -> str:
    return re.sub(r"[a-zA-Z]", "X", string)

#Apply function
[replace_letters_with_x(string) for string in remove_periods]

['XXXXXXXXXXX XX XXXXXXXXX XXXXXXXXX',
 'XXXXXXX XXX XXXXX XX XXXX XXXXXXX',
 'XXXXX XX XXX XXXXX XX XXXXX XXXXXXX']

---

### **6.2 Parsing and Cleaning HTML**


**Problem**
- You have text data with HTML elements and want to extract just the text

**Solution**
- Use Beautiful Soup's extensive set of options to parse and extract from HTML

In [12]:
#Load library
from bs4 import BeautifulSoup

#Create some HTML code 
html = """
        <div class='full_name'><span style='font-weight:bold'>
        Masego</span> Azra</div>"
    """
    
#Parse html
soup = BeautifulSoup(html)

#Find the div with the class "full_name", show text
soup.find("div", {"class": "full_name"}).text

'\n        Masego Azra'

---

### **6.3 Removing Punctuation**


**Problem**
- You have a feature of text data and want to remove punctuation

**Solution**
- Define a function that uses `translate` with a dictionary of punctuation characters

In [14]:
#Load libraries
import unicodedata
import sys

#Create text
text_data = ['Hi!!!! I. Love. This. Song....',
             '10000% Agree!!!! #LoveIT',
             'Right?!?!']

#Create a dictionary of punctuation characters
punctuation = dict.fromkeys(i for i in range(sys.maxunicode) if unicodedata.category(chr(i)).startswith('P'))

#For each string, remove any punctuation characters
[string.translate(punctuation) for string in text_data]

['Hi I Love This Song', '10000 Agree LoveIT', 'Right']

---


### **6.4 Tokenizing Text**

**Problem**
- You have text and want to break it up into individual words

**Solution**
- Natural Language Toolkit for Python (NLTK) has a powerful set of text manipulation operations, including word tokenizing:

In [3]:
#Load library 
from nltk.tokenize import word_tokenize

#Create text
string = 'The science of today is the technology of tomorrow'

#Tokenize words
word_tokenize(string)

['The', 'science', 'of', 'today', 'is', 'the', 'technology', 'of', 'tomorrow']

Tokenize into sentences

In [5]:
#Load library
from nltk import sent_tokenize

#Create text
string = "The science of today is the technology of tomorrow. Tomorrow is today."

#Tokenize sentences
sent_tokenize(string)

['The science of today is the technology of tomorrow.', 'Tomorrow is today.']

---

### **6.5 Removing Stop Words**

**Problem**
- Given tokenized text data, you want to remove extremely common words that contain little informational value.

**Solution**
- Use NLTK's `stopwords`

In [1]:
#Load library
from nltk.corpus import stopwords

#You will have to download the set of stop words the first time 
#import nltk
#nltk.download('stopwords')

#Create word tokens
tokenized_words = ['i', 'am', 'going', 'to', 'go', 'to', 'the', 'store', 'and', 'park']

#Load stop words
stop_words = stopwords.words('english')

#Remove stop words 
[word for word in tokenized_words if word not in stop_words]

['going', 'go', 'store', 'park']

---

### **6.6 Stemming Words**

**Problem**
- You have tokenized words and want to convert them into their root forms

**Solution**
- Use NLTK's `PorterStemmer`

In [2]:
#Load library
from nltk.stem.porter import PorterStemmer

#Create word tokens
tokenized_words = ['i', 'am', 'humbled', 'by', 'this', 'traditional', 'meeting']

#Create stemmer
porter = PorterStemmer()

#Apply stemmer
[porter.stem(word) for word in tokenized_words]

['i', 'am', 'humbl', 'by', 'thi', 'tradit', 'meet']

---

### **6.7 Tagging Parts of Speech**

**Problem**
- You have text data and want to tag each word or character with its part of speech

**Solution**
- Use NLTK's pre-trained parts-of-speech tagger

In [3]:
#Load libaries 
from nltk import pos_tag
from nltk import word_tokenize

#Create text
text_data = 'Chris loved outdoor running'

#Use pre-trained part of speech tagger
text_tagged = pos_tag(word_tokenize(text_data))

#Show parts of speech
text_tagged

[('Chris', 'NNP'), ('loved', 'VBD'), ('outdoor', 'RP'), ('running', 'VBG')]

Use the tags to find certain parts of speech. For example, here are all nouns

In [4]:
#Filter words
[word for word, tag in text_tagged if tag in ['NN', 'NNS', 'NNP', 'NNPS']]

['Chris']

Convert those sentences into features for individual parts of speech

In [6]:
from sklearn.preprocessing import MultiLabelBinarizer

In [9]:
#Create text
tweets = ["I am eating a burrito for breakfast", 
          "Political science is a amazing field",
          "San Francisco is a awesome city"]

#Create list
tagged_tweets = []

#Tag each word and each tweet
for tweet in tweets:
    tweet_tag = pos_tag(word_tokenize(tweet))
    tagged_tweets.append([tag for word, tag in tweet_tag])
    
#Use one-hot encoding to convert the tags into features
one_hot_multi = MultiLabelBinarizer()
one_hot_multi.fit_transform(tagged_tweets)

array([[1, 1, 0, 1, 0, 1, 1, 1, 0],
       [1, 0, 1, 1, 0, 0, 0, 0, 1],
       [1, 0, 1, 1, 1, 0, 0, 0, 1]])

In [10]:
#Show feature names 
one_hot_multi.classes_

array(['DT', 'IN', 'JJ', 'NN', 'NNP', 'PRP', 'VBG', 'VBP', 'VBZ'],
      dtype=object)

---

### **6.8 Encoding Text as a Bag of Words**

**Problem**
- You have text data and want to create a set of features indicating the number of times an observation's text contains a particular word.

**Solution**
- Use scikit-learn's `CountVectorizer`

In [11]:
#Load library
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer

#Create text 
text_data = np.array(["I love Brazil. Brazil!",
                      "Sweden is best", 
                      "Germany beats both"])

#Create the bag of words feature matrix
count = CountVectorizer()
bag_of_words = count.fit_transform(text_data)

#Show feature matrix
bag_of_words

<3x8 sparse matrix of type '<class 'numpy.int64'>'
	with 8 stored elements in Compressed Sparse Row format>

In [12]:
bag_of_words.toarray()

array([[0, 0, 0, 2, 0, 0, 1, 0],
       [0, 1, 0, 0, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 0, 0]], dtype=int64)

In [14]:
#Show feature names
count.get_feature_names_out()

array(['beats', 'best', 'both', 'brazil', 'germany', 'is', 'love',
       'sweden'], dtype=object)

---

### **6.9 Weighting Word Importance**

**Problem**
- You want a bag of words, but with words weighted by their importance to an observation

**Solution**
- Compare the frequency of the word in a document with the frequency of the word in all other documents using term frequency-inverse document frequency. scikit-learn makes this easy with `TfidfVectorized`

In [15]:
#Load libraries
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer

#Create text
text_data = np.array(['I love Brazil. Brazil!',
                      'Sweden is best',
                      'Germany beats both'])

#Create the tf-idf feature matrix
tfidf = TfidfVectorizer()
feature_matrix = tfidf.fit_transform(text_data)

#Show tf-idf feature matrix
feature_matrix

<3x8 sparse matrix of type '<class 'numpy.float64'>'
	with 8 stored elements in Compressed Sparse Row format>

In [17]:
feature_matrix.toarray()

array([[0.        , 0.        , 0.        , 0.89442719, 0.        ,
        0.        , 0.4472136 , 0.        ],
       [0.        , 0.57735027, 0.        , 0.        , 0.        ,
        0.57735027, 0.        , 0.57735027],
       [0.57735027, 0.        , 0.57735027, 0.        , 0.57735027,
        0.        , 0.        , 0.        ]])

In [16]:
#Show feature names
tfidf.vocabulary_

{'love': 6,
 'brazil': 3,
 'sweden': 7,
 'is': 5,
 'best': 1,
 'germany': 4,
 'beats': 0,
 'both': 2}

$$\mathrm{tf-idf}(t, d) = tf(t,d) \times idf(t)$$

$$\mathrm{idf}(t) = \log \frac{1 + n_d}{1 + \mathrm{df}(d, t)} + 1$$

---