<center>
    <h1>
        <b>Chapter 4. Handling Numerical Data</b>
    </h1>
</center>

----

### **4.0 Introduction**

----

### **4.1 Rescaling a Feature**

**Problem**
- You need to rescale the values of a numerical feature to be between two values.

**Solution**
- Use scikit-learn's `MinMaxScaler` to rescale a feature array

In [1]:
#Load library
import numpy as np
from sklearn import preprocessing

#Create feature
feature = np.array([[-500.5],
                    [-100.1],
                    [0],
                    [100.1],
                    [900.9]])

#Create scaler
minmax_scale = preprocessing.MinMaxScaler(feature_range=(0, 1))

#Scale feature
scaled_feature = minmax_scale.fit_transform(feature)

#Show features
print(scaled_feature)

[[0.        ]
 [0.28571429]
 [0.35714286]
 [0.42857143]
 [1.        ]]


**Min-max formula**

$$x'_i = \frac{x_i - min(x)}{max(x) - min(x)}$$

----

### **4.2 Standardizing a Feature**

**Problem**
- You want to transform a feature to have a mean of 0 and a standard deviation of 1

**Solution**
- scikit-learn's `StandarScaler` performs both transformations

In [2]:
#Load libraries
import numpy as np
from sklearn import preprocessing

#Create feature
x = np.array([[-1000.1],
              [-200.2],
              [500.5],
              [600.6],
              [9000.9]])

#Create scaler
scaler = preprocessing.StandardScaler()

#Transform the feature
standardized = scaler.fit_transform(x)

#Show feature
print(standardized)

[[-0.76058269]
 [-0.54177196]
 [-0.35009716]
 [-0.32271504]
 [ 1.97516685]]


**Standardized formula**

$$x'_i = \frac{x_i - \bar{x}}{\sigma}$$

----

### **4.3 Normalizing Observations**

**Problem**
- You want to rescale the feature values of observations to have unit norm (a total length of 1)

**Solution**
- Use `Normalizer` with a `norm` argument

In [3]:
#Load libraries
from locale import normalize
import numpy as np
from sklearn.preprocessing import Normalizer

#Create feature matrix
features = np.array([[0.5, 0.5],
                    [1.1, 3.4],
                    [1.5, 20.2],
                    [1.63, 34.4],
                    [10.9, 3.3]])

#Create normalizer
normalizer = Normalizer(norm="l2")

#Transform feature matrix
print(normalizer.transform(features))

[[0.70710678 0.70710678]
 [0.30782029 0.95144452]
 [0.07405353 0.99725427]
 [0.04733062 0.99887928]
 [0.95709822 0.28976368]]


**L2 Norm**

$$||x||_2 = \sqrt{\sum_{i=1}^n x^2_i}$$

**L1 Norm**

$$||x||_1 = \sum^n_{i=1}|x_i|$$

----

### **4.4 Generating Polynomial and Interaction Features**

**Problem**
- You want to create polynominal and interaction features.

**Solution**
- Even though some choose to create polynomial and interaction features manually, scikit-learn offers a built-in method:

In [1]:
#load libraries 
import numpy as np
from sklearn.preprocessing import PolynomialFeatures

#Create feature matrix
features = np.array([[2, 3],
                     [2, 3],
                     [2, 3]])

#Create PolynomialFeatures object
polynomial_interaction = PolynomialFeatures(degree=2, include_bias=False)

#Create polynomial features
polynomial_interaction.fit_transform(features)

array([[2., 3., 4., 6., 9.],
       [2., 3., 4., 6., 9.],
       [2., 3., 4., 6., 9.]])

We can restrict the features created to only interaction features by setting `interaction_only` to `True`

In [2]:
interaction = PolynomialFeatures(degree=2,
                                 interaction_only=True,
                                 include_bias=False)

interaction.fit_transform(features)

array([[2., 3., 6.],
       [2., 3., 6.],
       [2., 3., 6.]])

----

### **Transforming Features**

**Problem**
- You want to make a custom transformation to one or more features.

**Solution**
- In scikit-learn, use `FunctionTransformer` to apply a function to set of features.

In [3]:
#Load libraries
import numpy as np
from sklearn.preprocessing import FunctionTransformer

#Create features matrix
features = np.array([[2, 3],
                     [2, 3],
                     [2, 3]])

#Define a simple function
def add_ten(x):
    return x + 10

#Create transformer
ten_transformer = FunctionTransformer(add_ten)

#Transform feature matrix
ten_transformer.transform(features)

array([[12, 13],
       [12, 13],
       [12, 13]])

Use with Pandas

In [4]:
#Load library
import pandas as pd

#Create DataFrame
df = pd.DataFrame(features, columns=['feature_1', 'feature_2'])

#Apply function
df.apply(add_ten)

feature_1  feature_2
0         12         13
1         12         13
2         12         13

----

### **Detecting Outliers**

**Problem**
- You want to identify extreme observations

**Solution**



In [5]:
#Load libraries
import numpy as np
from sklearn.covariance import EllipticEnvelope
from sklearn.datasets import make_blobs

#Create simulated data
features, _ = make_blobs(n_samples=10,
                         n_features=2,
                         centers=1,
                         random_state=1)

#Replace the first observation's values with extreme values
features[0, 0] = 10000
features[0, 1] = 10000

#Create detector 
outlier_detector = EllipticEnvelope(contamination=.1)

#Fit detector
outlier_detector.fit(features)

#Predict outliers
outlier_detector.predict(features)

array([-1,  1,  1,  1,  1,  1,  1,  1,  1,  1])

In [6]:
#Create one feature
feature = features[:, 0]

#Create a function to return index of outliers
def indicies_of_outliers(x):
    q1, q3 = np.percentile(x, [25, 75])
    iqr = q3 - q1
    lower_bound = q1 - (iqr * 1.5)
    upper_bound = q3 + (iqr * 1.5)
    return np.where((x > upper_bound) | (x < lower_bound))

#Run function
indicies_of_outliers(feature)

(array([0], dtype=int64),)

----

### **4.7 Handling Outliers**

**Problem**
- You have outliers

**Solution**
- Typically we have three strategies we can use to handle outliers. First, we can drop them

In [7]:
#Load library
import pandas as pd

#Create DataFrame
houses = pd.DataFrame()
houses['Price'] = [534433, 392333, 293222, 4322032]
houses['Bathrooms'] = [2, 3.5, 2, 116]
houses['Square_Feet'] = [1500, 2500, 1500, 48000]

#Filter observations
houses[houses['Bathrooms'] < 20] 

Price  Bathrooms  Square_Feet
0  534433        2.0         1500
1  392333        3.5         2500
2  293222        2.0         1500

Second, we can mark them as outliers and include it as a feature

In [8]:
#Load library
import numpy as np

#Create feature based on boolean condition
houses['Outlier'] = np.where(houses['Bathrooms'] < 20, 0, 1)

#Show data
houses

Price  Bathrooms  Square_Feet  Outlier
0   534433        2.0         1500        0
1   392333        3.5         2500        0
2   293222        2.0         1500        0
3  4322032      116.0        48000        1

Finally, we can transform the feature to dampen the effect of the outlier

In [12]:
#Log feature
houses["Log_Of_Square_Feet"] = [np.log(x) for x in houses['Square_Feet']]

#Show data
houses

Price  Bathrooms  Square_Feet  Outlier  Log_Of_Square_Feet
0   534433        2.0         1500        0            7.313220
1   392333        3.5         2500        0            7.824046
2   293222        2.0         1500        0            7.313220
3  4322032      116.0        48000        1           10.778956

----

### **Discretizating Features**

**Problem**
- You have a numerical feature and want to break it up into discrete bins

**Solution**
- Depending on how we want to break up the data, there are two techniques we can use. First, we can binarize the feature according to some threshold

In [16]:
#Load libraries 
import numpy as np
from sklearn.preprocessing import Binarizer

#Create feature
age = np.array([[6],
                [12],
                [20],
                [36],
                [65]])

#Create binarizer
binarizer = Binarizer(threshold=18)

#Transform feature
binarizer.fit_transform(age)

array([[0],
       [0],
       [1],
       [1],
       [1]])

Second, we can break up numerical features according to multiple thresholds

In [17]:
#Bin feature
np.digitize(age, bins=[20, 30, 64])

array([[0],
       [0],
       [1],
       [2],
       [3]], dtype=int64)

----

### **4.9 Grouping Observations Using Clustering**

**Problem**
- You want to cluster observations so that similar observations are grouped together

**Solution**
- If you know that you have *k* groups, you can use k-means clustering to group similar observations and output a new feature containing each observation's group membership

In [18]:
#Load libraries
import numpy as np
import pandas as pd
from sklearn.datasets import make_blobs
from sklearn.cluster import KMeans

#make simulated feature matrix
features, _ = make_blobs(n_samples=50, 
                         n_features=2,
                         centers=3,
                         random_state=1)

#Create DataFrame
dataframe = pd.DataFrame(features, columns=['feature_1', 'feature_2'])

#Make k-means clusterer
clusterer = KMeans(3, random_state=0)

#Fit clusterer
clusterer.fit(features)

#Predict values
dataframe['group'] = clusterer.predict(features)

#View first few observations
dataframe.head(5)

feature_1  feature_2  group
0  -9.877554  -3.336145      0
1  -7.287210  -8.353986      2
2  -6.943061  -7.023744      2
3  -7.440167  -8.791959      2
4  -6.641388  -8.075888      2

----

### **Deleting Observations with Missing Values**

**Problem**
- You need delete observations containing missing values

**Solution**
- Deleting observations with missing values is easy with a clever line of NumPy

In [19]:
#Load library
import numpy as np

#Create feature matrix
features = np.array([[1.1, 11.1],
                     [2.2, 22.2],
                     [3.3, 33.3],
                     [4.4, 44.4],
                     [np.nan, 55]])

#Keep only observations that are not (denoted by ~) missing
features[~np.isnan(features).any(axis=1)]

array([[ 1.1, 11.1],
       [ 2.2, 22.2],
       [ 3.3, 33.3],
       [ 4.4, 44.4]])

In [20]:
#Load library
import pandas as pd

#Load data
dataframe = pd.DataFrame(features, columns=['feature 1', 'feature 2'])

#Remove observations with missing values
dataframe.dropna()

feature 1  feature 2
0        1.1       11.1
1        2.2       22.2
2        3.3       33.3
3        4.4       44.4

----

### **4.11 Imputing Missing Values**

**Problem**
- You have missing values in your data and want to fill in or predict their values

**Solution**
- If you have a small amount of data, predict the missing values using k-nearest neighbors (KNN):

In [23]:
#Load libraries
import numpy as np
from fancyimpute import KNN
from sklearn.preprocessing import StandardScaler
from sklearn.datasets import make_blobs

#Make a simulated feature matrix
features, _ = make_blobs(n_samples=1000,
                         n_features=2,
                         random_state=1)

#Standardize the features
scaler = StandardScaler()
standardized_features = scaler.fit_transform(features)

#Replace the first feature's first value with a missing value
true_value = standardized_features[0, 0]
standardized_features[0, 0] = np.nan

#Predict the missing values in the feature matrix
features_knn_imputed = KNN(k=5, verbose=0).fit_transform(standardized_features)

#Compare true and imputed values
print('True  value:', true_value)
print('Imputed  value:', features_knn_imputed[0, 0])

True  value: 0.8730186113995938
Imputed  value: 1.0955332713113226
