<center>
    <h1>
        <b>
            Chapter 5. Handling Categorical Data
        </b>
    </h1>
</center>

---

### **5.0 Introduction**

---

### **5.1 Encoding Nominal Categorical Features**

**Problem**
- You havea feature with nominal classes that has no intrisic ordering

**Solution**
- One-hot encode the feature using scikit-learn's `LabelBinarizer`

In [1]:
#Import libraries
import numpy as np
from sklearn.preprocessing import LabelBinarizer, MultiLabelBinarizer

#Create feature
feature = np.array([['Texas'],
                    ['California'],
                    ['Texas'],
                    ['Delaware'],
                    ['Texas']])

#Create one-hot encoder
one_hot = LabelBinarizer()

#One-hot encode feature
one_hot.fit_transform(feature)

array([[0, 0, 1],
       [1, 0, 0],
       [0, 0, 1],
       [0, 1, 0],
       [0, 0, 1]])

Use the `classes_` method to output the classes

In [2]:
#View feature classes
one_hot.classes_

array(['California', 'Delaware', 'Texas'], dtype='<U10')

Reverse the one-hot encoding, we can use `inverse_transform`

In [3]:
one_hot.inverse_transform(one_hot.fit_transform(feature))

array(['Texas', 'California', 'Texas', 'Delaware', 'Texas'], dtype='<U10')

Use pandas to one-hot encode the feature

In [6]:
#Import library
import pandas as pd

#Create dummy variables from feature
pd.get_dummies(feature[:, 0])

California  Delaware  Texas
0           0         0      1
1           1         0      0
2           0         0      1
3           0         1      0
4           0         0      1

Multiple classes 

In [7]:
#Create multiclass feature
multiclass_features = [('Texas', 'Floria'),
                       ('California', 'Alabama'),
                       ('Texas', 'Floria'),
                       ('Delware', 'Floria'),
                       ('Texas', 'Alabama')]

#Create multiclass one-hot encoder
one_hot_multiclass = MultiLabelBinarizer()

#One-hot encode multiclass feature
one_hot_multiclass.fit_transform(multiclass_features)

array([[0, 0, 0, 1, 1],
       [1, 1, 0, 0, 0],
       [0, 0, 0, 1, 1],
       [0, 0, 1, 1, 0],
       [1, 0, 0, 0, 1]])

---

### **5.2 Encoding Ordinal Categorical Features**

**Problem**
- You have an ordinal categorical feature

**Solution**
- Use pandas DataFrame's `replace` method to transform string labels to numerical equivalents

In [9]:
#Load library
import pandas as pd

#Create features
dataframe = pd.DataFrame({
    'Score': ["Low", "Low", "Medium", "Medium", "High"]
})

#Create mapper
scale_mapper = {
    'Low': 1,
    'Medium': 2,
    'High': 3
}

#Replace feature values with scale
dataframe['Score'].replace(scale_mapper)

0    1
1    1
2    2
3    2
4    3
Name: Score, dtype: int64

---

### **5.3 Encoding Dictionaries of Features**

**Problem**
- You have a dictionary and want to convert it into a feature matrix

**Solution**
- Use `DictVectorizer`


In [10]:
#Import library
from sklearn.feature_extraction import DictVectorizer

#Create dictionary
data_dict = [{'Red': 2, 'Blue': 4},
             {'Red': 4, 'Blue': 3},
             {'Red': 1, 'Yellow': 2},
             {'Red': 2, 'Yellow': 2}]

#Create dictionary vectorizer
dictvectorizer = DictVectorizer(sparse=False)

#Convert dictionary to feature matrix
features = dictvectorizer.fit_transform(data_dict)

#View feature matrix
features

array([[4., 2., 0.],
       [3., 4., 0.],
       [0., 1., 2.],
       [0., 2., 2.]])

Use the `get_feature_names` method:

In [12]:
#Get feature names
feature_names = dictvectorizer.get_feature_names_out()

#View feature names
feature_names

array(['Blue', 'Red', 'Yellow'], dtype=object)

---

### **5.4 Imputing Missing Class Values**

---

### **5.5 Handling Imbalanced Classes**

---